#!/bin/bash

printf "Delete everything from the cursor to the end of the line:\n"
printf "Ctrl + k\n"
printf "Delete everything from the cursor to the start of the line:\n"
printf "Ctrl + u\n"
printf "Delete one word backward from cursor:\n"
printf "Ctrl + w\n"
printf "Search your history backward.\n"
printf "Ctrl + r\n"
printf "Clear the screen, I use this instead of typing the clear command:\n"
printf "Ctrl + l\n"
printf "Stops the output to the screen:\n"
printf "Ctrl + s\n"
printf "Enable the output to the screen in case that previously stopped by Ctrl + s:\n"
printf "Ctrl + q\n"
printf "Terminate the current command\n"
printf "Ctrl + c\n"
printf "Throw the current command to background:\n"
printf "Ctrl + z\n"
